[DEFAULT]
# nbdev settings
lib_name = emachines
user = NaveenDeepak
author = ND
author_email = NaveenDeepak@gmail.com
description = Analytical electromechanical machine design library
keywords = electric motor PMSM BLDC winding electromagnetic electromechanical
license = apache2
copyright = ND
branch = main
version = 0.1.0
min_python = 3.9
audience = Science/Research
language = English
custom_sidebar = false
nbs_path = nbs
lib_path = emachines
doc_path = docs
doc_host = https://NaveenDeepak.github.io
doc_baseurl = /emachines
git_url = https://github.com/NaveenDeepak/emachines
